name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'

    - name: Print go version
      run: go version

    - name: Install dependencies
      run: ./scripts/configure_dev.sh

    - name: Install buildtools
      run: ./scripts/buildtools/install_buildtools.sh
  
    - name: Run build
      run: make
